# Generated by Django 3.0.6 on 2020-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='desc',
        ),
    ]
