# Generated by Django 3.0.6 on 2020-05-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment_adda.Subject'),
            preserve_default=False,
        ),
    ]
