# Generated by Django 3.0.6 on 2020-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0004_topic_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
