# Generated by Django 3.0.6 on 2001-12-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0006_auto_20200516_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
    ]
