# Generated by Django 3.0.6 on 2001-12-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0007_remove_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assignment_adda.Subject'),
            preserve_default=False,
        ),
    ]
