# Generated by Django 3.0.6 on 2020-05-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0009_auto_20200518_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
