# Generated by Django 3.0.6 on 2020-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0013_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
