# Generated by Django 3.0.6 on 2020-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0014_entry_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
