# Generated by Django 3.0.6 on 2020-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0016_auto_20200519_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(default='pics/default.jpg', upload_to='pics'),
        ),
    ]
