# Generated by Django 3.0.6 on 2020-06-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0017_auto_20200519_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
