# Generated by Django 3.0.6 on 2020-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0019_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='img',
            field=models.ImageField(upload_to='pics/header'),
        ),
    ]
