# Generated by Django 3.0.6 on 2020-06-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_adda', '0020_auto_20200610_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='theme',
        ),
    ]
