from django.db import models
from django.core.validators import RegexValidator
# from django import forms
from django.contrib.auth.models import User
import uuid
class Snip(models.Model):
    alphanumeric = RegexValidator(
        r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=40, default="Untitled")
    text = models.TextField()
    link_code = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4, editable=False)
    langs = [('text', 'None'),
            ('Markup', 'markup'),
            ('html', 'html'),
             ('CSS', 'css'),
             ('C-like', 'clike'),
             ('JavaScript', 'javascript, js'),
             ('Arduino', 'arduino'),
             ('Bash', 'bash, shell'),
             ('BASIC', 'basic'),
             ('C', 'c'),
             ('C#', 'csharp, cs, dotnet'),
             ('C++', 'cpp'),
             ('CoffeeScript', 'coffeescript, coffee'),
             ('CMake', 'cmake'),
             ('Clojure', 'clojure'),
             ('Django/Jinja2', 'django, jinja2'),
             ('Docker', 'docker, dockerfile'),
             ('Git', 'git'),
             ('GameMaker Language', 'gml, gamemakerlanguage'),
             ('Go', 'go'),
             ('GraphQL', 'graphql'),
             ('Groovy', 'groovy'),
             ('Haml', 'haml'),
             ('HTTP', 'http'),
             ('Icon', 'icon'),
             ('Java', 'java'),
             ('JavaDoc', 'javadoc'),
             ('JSDoc', 'jsdoc'),
             ('JSON', 'json'),
             ('JSONP', 'jsonp'),
             ('JSON5', 'json5'),
             ('Kotlin', 'kotlin'),
             ('LaTeX', 'latex, tex, context'),
             ('Latte', 'latte'),
             ('Less', 'less'),
             ('LiveScript', 'livescript'),
             ('Lua', 'lua'),
             ('Makefile', 'makefile'),
             ('Markdown', 'markdown, md'),
             ('MATLAB', 'matlab'),
             ('nginx', 'nginx'),
             ('Objective-C', 'objectivec'),
             ('OpenCL', 'opencl'),
             ('Parser', 'parser'),
             ('Pascal', 'pascal, objectpascal'),
             ('Perl', 'perl'),
             ('PHP', 'php'),
             ('PL/SQL', 'plsql'),
             ('PowerShell', 'powershell'),
             ('Pug', 'pug'),
             ('Python', 'python, py'),
             ('R', 'r'),
             ('React JSX', 'jsx'),
             ('React TSX', 'tsx'),
             ('Regex', 'regex'),
             ('Ruby', 'ruby, rb'),
             ('Rust', 'rust'),
             ('SAS', 'sas'),
             ('Sass (Sass)', 'sass'),
             ('Sass (Scss)', 'scss'),
             ('Scala', 'scala'),
             ('SQL', 'sql'),
             ('Stylus', 'stylus'),
             ('Swift', 'swift'),
             ('Twig', 'twig'),
             ('TypeScript', 'typescript, ts'),
             ('Velocity', 'velocity'),
             ('vim', 'vim'),
             ('Visual Basic', 'visual-basic, vb'),
             ('Wiki markup', 'wiki'),
             ('YAML', 'yaml, yml'),
             ('Zig', 'zig'),
                ]
    themes = [('default', 'None'),
             ('atom-dark', 'atom-dark'),
             ('cB', 'cb'),
             ('coy', 'coy'),
             ('darcula', 'darcula'),
             ('dark', 'dark'),
             ('duotone-dark', 'duotone-dark'),
             ('duotone-earth', 'duotone-earth'),
             ('duotone-forest', 'duotone-forest'),
             ('duotone-light', 'duotone-light'),
             ('duotone-sea', 'duotone-sea'),
             ('duotone-space', 'duotone-space'),
             ('funky', 'funky'),
             ('ghcolors', 'ghcolors'),
             ('hopscotch', 'hopscotch'),
             ('light', 'light'),
             ('material-dark', 'material-dark'),
             ('material-light', 'material-light'),
             ('okaidia', 'okaidia'),
             ('shades-of-purple', 'shades-of-purple'),
             ('solarizedlight', 'solarizedlight'),
             ('tomorrow', 'tomorrow'),
             ('twilight', 'twilight'),
             ('vs', 'vs'),
             ('vsc-dark-plus', 'vsc-dark-plus'),
             ('xonokai', 'xonokai'),
             ]
    lang = models.CharField(max_length=18, choices=langs, default='text')
    theme = models.CharField(max_length=18, choices=themes, default='default')
    lines = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.link_code+" : "+self.text[:20]