# Generated by Django 3.0.6 on 2020-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='user',
        ),
    ]
