# Generated by Django 3.0.6 on 2020-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='theme',
            field=models.CharField(choices=[('Default', 'None'), ('Atom-dark', 'atom-dark'), ('CB', 'cb'), ('Coy', 'coy'), ('Darcula', 'darcula'), ('Dark', 'dark'), ('Duotone-dark', 'duotone-dark'), ('Duotone-earth', 'duotone-earth'), ('Duotone-forest', 'duotone-forest'), ('Duotone-light', 'duotone-light'), ('Duotone-sea', 'duotone-sea'), ('Duotone-space', 'duotone-space'), ('Funky', 'funky'), ('Ghcolors', 'ghcolors'), ('Hopscotch', 'hopscotch'), ('Light', 'light'), ('Material-dark', 'material-dark'), ('Material-light', 'material-light'), ('Okaidia', 'okaidia'), ('Shades of purple', 'shades-of-purple'), ('Solarized light', 'solarizedlight'), ('Tomorrow', 'tomorrow'), ('Twilight', 'twilight'), ('VS', 'vs'), ('VS dark', 'vsc-dark-plus'), ('Xonokai', 'xonokai')], default='Default', max_length=18),
        ),
    ]
