# Generated by Django 3.0.6 on 2020-06-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0002_snip_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='theme',
            field=models.CharField(choices=[('default', 'None'), ('atom-dark', 'atom-dark'), ('cB', 'cb'), ('coy', 'coy'), ('darcula', 'darcula'), ('dark', 'dark'), ('duotone-dark', 'duotone-dark'), ('duotone-earth', 'duotone-earth'), ('duotone-forest', 'duotone-forest'), ('duotone-light', 'duotone-light'), ('duotone-sea', 'duotone-sea'), ('duotone-space', 'duotone-space'), ('funky', 'funky'), ('ghcolors', 'ghcolors'), ('hopscotch', 'hopscotch'), ('light', 'light'), ('material-dark', 'material-dark'), ('material-light', 'material-light'), ('okaidia', 'okaidia'), ('shades-of-purple', 'shades-of-purple'), ('solarizedlight', 'solarizedlight'), ('tomorrow', 'tomorrow'), ('twilight', 'twilight'), ('vs', 'vs'), ('vsc-dark-plus', 'vsc-dark-plus'), ('xonokai', 'xonokai')], default='default', max_length=18),
        ),
    ]
