# Generated by Django 3.0.6 on 2020-06-25 13:25

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0003_snip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='link_code',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7),
        ),
    ]
