# Generated by Django 3.0.6 on 2020-06-25 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0004_auto_20200625_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='link_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
