# Generated by Django 3.0.6 on 2020-06-25 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snipshare', '0005_auto_20200625_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='id',
        ),
        migrations.AlterField(
            model_name='snip',
            name='link_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
