# Generated by Django 3.0.6 on 2020-06-25 10:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200615_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
